# -*- coding: utf-8 -*-
"""FaceDetect.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AE-Az8LqN8HPgzT0xODYS5nNDPcI8vKg
"""

import cv2
import os

def extract_faces_from_video(video_path, output_dir, frame_count):
    # Tạo thư mục output nếu chưa tồn tại
    os.makedirs(output_dir, exist_ok=True)

    # Khởi tạo bộ phát hiện khuôn mặt
    face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')

    # Đọc video
    cap = cv2.VideoCapture(video_path)
    total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
    frame_step = max(1, total_frames // frame_count)

    frame_index = 0
    saved_faces = 0

    while cap.isOpened():
        ret, frame = cap.read()
        if not ret:
            break

        if frame_index % frame_step == 0:
            # chuyển sang màu xám để tăng độ chính xác
            gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
            # phát hiện face
            faces = face_cascade.detectMultiScale(gray, scaleFactor=1.1, minNeighbors=5, minSize=(30, 30))

            for i, (x, y, w, h) in enumerate(faces):
                face = frame[y:y+h, x:x+w]
                face_filename = os.path.join(output_dir, f"frame_{frame_index}_face_{i}.jpg")
                cv2.imwrite(face_filename, face)
                saved_faces += 1

        frame_index += 1

    cap.release()
    print(f"Đã lưu {saved_faces} khuôn mặt vào thư mục '{output_dir}'")

video_path = "id0_id1_0000.mp4"              # Thay bằng đường dẫn tới video
output_dir = "output_faces"           # Thư mục để lưu khuôn mặt
max_frame = 50
extract_faces_from_video(video_path, output_dir, max_frame)