# -*- coding: utf-8 -*-
"""VideoToFrame.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13NGoOPUTqcPQz3eS7LQRMGHkGhA9PUq6
"""

import kagglehub
kagglehub.login()

deepfake_data_path = kagglehub.dataset_download('hungle3401/faceforensics')
print('Data source import complete.')

! kaggle datasets download hungle3401/faceforensics

! unzip faceforensics.zip

import cv2
import os

# Đường dẫn đến video
video_path = '/content/FF/fake/01_02__outside_talking_still_laughing__YVGY8LOK.mp4'
# Thư mục lưu các frame
output_folder = '/content/output/output_1'

# Tạo thư mục nếu chưa có
if not os.path.exists(output_folder):
    os.makedirs(output_folder)

# Mở video
vidcap = cv2.VideoCapture(video_path)
success, image = vidcap.read()
count = 0

max_frames = 40

# Đọc và lưu từng frame
while success and count<max_frames:
    # Đặt tên file và lưu frame
    frame_filename = os.path.join(output_folder, f"frame{count:03d}.jpg")
    cv2.imwrite(frame_filename, image)

    # Đọc frame tiếp theo
    success, image = vidcap.read()
    print(f'Read a new frame: {success}')
    count += 1

# Giải phóng tài nguyên
vidcap.release()
print(f'Đã lưu {count} frames tại {output_folder}')

#import from FF/fake
import os

folder_path = '/content/FF/fake'

files = os.listdir(folder_path)

print("Các file trong thư mục:")
for file in files:
    print(file)

print(f"Tổng số file trong thư mục: {len(files)}")

#split data from FF/fake
import cv2
import os

input_folder = '/content/FF/fake'
output_base_folder = '/content/output_frames'
max_frames = 40

if not os.path.exists(output_base_folder):
    os.makedirs(output_base_folder)

for idx, filename in enumerate(os.listdir(input_folder), start=1):
    video_path = os.path.join(input_folder, filename)

    if not filename.endswith('.mp4'):
        continue

    output_folder = os.path.join(output_base_folder, f'output_{idx}')
    os.makedirs(output_folder, exist_ok=True)

    vidcap = cv2.VideoCapture(video_path)
    success, image = vidcap.read()
    count = 0

    while success and count < max_frames:
        frame_filename = os.path.join(output_folder, f"frame{count:02d}.jpg")
        cv2.imwrite(frame_filename, image)

        success, image = vidcap.read()
        count += 1

    vidcap.release()
    print(f"Đã lưu {count} frames của video '{filename}' tại {output_folder}")

print("Hoàn thành xử lý tất cả các video!")

#split from FF/real
import os

folder_path = '/content/FF/real'

files = os.listdir(folder_path)

print("Các file trong thư mục:")
for file in files:
    print(file)

print(f"Tổng số file trong thư mục: {len(files)}")

#split data from FF/fake
import cv2
import os

input_folder = '/content/FF/real'
output_base_folder = '/content/output_frames_real'
max_frames = 40

if not os.path.exists(output_base_folder):
    os.makedirs(output_base_folder)

for idx, filename in enumerate(os.listdir(input_folder), start=1):
    video_path = os.path.join(input_folder, filename)

    if not filename.endswith('.mp4'):
        continue

    output_folder = os.path.join(output_base_folder, f'output_{idx}')
    os.makedirs(output_folder, exist_ok=True)

    vidcap = cv2.VideoCapture(video_path)
    success, image = vidcap.read()
    count = 0

    while success and count < max_frames:
        frame_filename = os.path.join(output_folder, f"frame{count:02d}.jpg")
        cv2.imwrite(frame_filename, image)

        success, image = vidcap.read()
        count += 1

    vidcap.release()
    print(f"Đã lưu {count} frames của video '{filename}' tại {output_folder}")

print("Hoàn thành xử lý tất cả các video!")

from google.colab import files

# Nén thư mục output_frames thành file .zip
!zip -r output_frames.zip output_frames

# Tải file .zip về máy
files.download('output_frames.zip')

!zip -r output_frames_real.zip output_frames_real

# Tải file .zip về máy
files.download('output_frames_real.zip')